{% set name = "sgp4" %}
{% set version = "2.0" %}
{% set gh_org = "brandon-rhodes" %}
{% set gh_repo = "python-sgp4" %}
{% set sha256 = "c6aab698e99a383bda8ae9b9a727caa483da5d3b2e33f15de62851ffb4f9334a" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/{{ gh_org }}/{{ gh_repo }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - manifest.patch
    - tests.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  requires:
    - numpy
  imports:
    - sgp4
    - sgp4.tests
  commands:
    - python -m unittest -v sgp4.tests

about:
  home: https://github.com/brandon-rhodes/python-sgp4
  license: MIT
  license_file: {{ environ.RECIPE_DIR }}/LICENSE
  summary: 'Python implementation of most recent version of the SGP4 satellite tracking algorithm.'

  description: |
    Python implementation of most recent version
    of the SGP4 satellite tracking algorithm.

extra:
  recipe-maintainers:
    - jochym
    - brandon-rhodes
