{% set name = "sgp4" %}
{% set version = "2.13" %}
{% set sha256 = "3acdbbb5de380b587c66fc59e26e635668c74661da1b731007aece8506d1e279" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sgp4/sgp4-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - test-precission.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
  run:
    - python

test:
  requires:
    - numpy
  imports:
    - sgp4
    - sgp4.tests
  commands:
    - python -m unittest -v sgp4.tests

about:
  home: https://github.com/brandon-rhodes/python-sgp4
  license: MIT
  license_file: {{ environ.RECIPE_DIR }}/LICENSE
  summary: Python implementation of most recent version of the SGP4 satellite tracking algorithm.

  description: |
    Python implementation of most recent version
    of the SGP4 satellite tracking algorithm.

extra:
  recipe-maintainers:
    - jochym
    - brandon-rhodes
