{% set name = "sgp4" %}
{% set version = "1.4" %}
{% set sha256 = "1fb3cdbc11981a9ff34a032169f83c1f4a2877d1b6c295aed044e1d890b73892" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - manifest.patch
    - tests.patch

build:
  noarch: python
  number: 5
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  requires:
    - numpy
  imports:
    - sgp4
    - sgp4.tests
  commands:
    - python -m unittest -v sgp4.tests

about:
  home: https://github.com/brandon-rhodes/python-sgp4
  license: MIT
  license_file: {{ environ.RECIPE_DIR }}/LICENSE
  summary: 'Python implementation of most recent version of the SGP4 satellite tracking algorithm.'

  description: |
    Python implementation of most recent version
    of the SGP4 satellite tracking algorithm.

extra:
  recipe-maintainers:
    - jochym
    - brandon-rhodes
