{% set name = "sgp4" %}
{% set version = "2.25" %}
{% set sha256 = "e19edc6dcc25d69fb8fde0a267b8f0c44d7e915c7bcbeacf5d3a8b595baf0674" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/sgp4/sgp4-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - setuptools
    - python
  run:
    - python

test:
  requires:
    - numpy *
  imports:
    - sgp4
    - sgp4.tests
  commands:
    - python -m unittest -v sgp4.tests

about:
  home: https://github.com/brandon-rhodes/python-sgp4
  license: MIT
  license_file: {{ environ.RECIPE_DIR }}/LICENSE
  summary: Python implementation of most recent version of the SGP4 satellite tracking algorithm.

  description: |
    Python implementation of most recent version
    of the SGP4 satellite tracking algorithm.

extra:
  recipe-maintainers:
    - jochym
    - brandon-rhodes
