travis:
  secure:
    BINSTAR_TOKEN: T1TWvWOkUkVEQtrFyEeSqwH2I8iFQ3u+HYoKYcUBc2RfgY7x2NqV3Eim65hJmEO3ATebC0DJLMG5MW6PcxZzYr/4P8Vm1f5gkmDOL9IxLEKhDQEDpQ8Bdekqohf66uWVXpMgu72zoiqGQSXwCALAkLuXl+3CjbSET+zvlwWRocrnJ2kbvSdh/1GQI1WwaEbP/m9FmXbBhb2qebujnzUX6KwPKWyDI40/7+zLvtlu1Gmmw638XjpJDaWbww1GocsHZjCa9x1C4j7zvLI8tYPG1VakQH4KYEj0b+H7zxJ0KuiCcdp50F0m1GTnzgHLQku4+jQhdYz0wMr9qpTlwYpX0ZqwMPpOxOgb8B5509dpI2usvCkArWBfpE/3nriVxxmAvtu1Rm0SxUTFNrb0dluX1OODu3w54xaUMaPcog+lZ9O1hGlWkY+uqj0VkggRKEzitjMoOP/7CvZwXcPIKoWw8jE+k/pyTNILbegCtBwD9ncHHhhzm+rm8963L9B96sqtkJ9xBBtiFhQP5YJZf4McTlXMRhIZ4cRJ4LrjTy9ISns2J9FHs4yUgXw2MA5MAgtbMoZvLQnpBwtoeLcTw3v+487Pz40HyPnEDc32kiuk6RdYnIZthmP3SjRw8AcDK4Zrp/5IzroYp6STEYesra2lrQMr8dGRvO/Eup7DKbOogMY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
